### ISSUE TITLE
You don't have access to Google Drive resource

### ISSUE THREAD

**Issue by padak** [keboola/google-drive-writer#13]
Klienti někdy vidí tenhle error v eventu jobu (job sám končí OK):

```
wr-google-drive.WARNING: You don't have access to Google Drive resource. [] []
```
(https://connection.eu-central-1.keboola.com/admin/projects/194/jobs/4761045?q=%2Bparams.component%3Akeboola.wr-google-drive%20%2Bparams.config%3A359223534&eventId=46515146)

**Comment by MiroCillik** [comment]
Scopama to teda neni

**Comment by MiroCillik** [comment]
FIXED in https://github.com/keboola/google-drive-writer/commit/dc3ee421966a4cfb3ff2517a3e9f259a117fbe92
