### ISSUE TITLE
Synchronise sheets KBC -> Google Drive

### ISSUE THREAD

**Issue by MiroCillik** [keboola/google-drive-writer#6]
Type: spreadsheet
Action: update | append

Synchronise sheets one way KBC -> Google Drive. 
If user delete sheet in Google Drive, but it is configured in KBC, the sheet will be created in Google Drive upon "run".
If user delete sheet in KBC, the sheet will be deleted in Google Drive upon "run".
This feature should be optional.

**Comment by padak** [comment]
Pokud se smaže sheet v kbc, zeptal bych se jestli ho máme smazat i v gdrive a neříkal tomu sync. Pokud se smaže v gdrive, hodil bych Error by default. Jakej je usecase abysme to (automaticky) zakládali když to někdo smazal? 

Proč to není v ProductBoardu? Kdo to vymyslel a proč?
